// Copyright 2026 Gordios45 contributors
// SPDX-License-Identifier: Apache-2.0

// Package ifrc_go ingests public IFRC GO disaster/emergency events. The
// current unauthenticated v2 endpoint lives on goadmin.ifrc.org; the older
// go-api.ifrc.org endpoints require authorization and are intentionally not
// used here.
package ifrc_go

import (
	"context"
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"os/exec"
	"strings"
	"time"

	"github.com/gordios45/collector/internal/events"
	propx "github.com/gordios45/collector/internal/props"
)

const (
	sourceID      = "ifrc_go"
	eventsURL     = "http://goadmin.ifrc.org/api/v2/event/?limit=100&ordering=-created_at"
	countriesURL  = "http://goadmin.ifrc.org/api/v2/country/?limit=400"
	sourcePublic  = "https://go.ifrc.org/"
	sourceKind    = "official_humanitarian_disaster_event_feed"
	maxEventCount = 100
)

type Collector struct{}

func New() (*Collector, error)                { return &Collector{}, nil }
func (c *Collector) ID() string               { return sourceID }
func (c *Collector) PollEvery() time.Duration { return 30 * time.Minute }

type eventResponse struct {
	Results []goEvent `json:"results"`
}

type goEvent struct {
	ID                      int         `json:"id"`
	Name                    string      `json:"name"`
	DType                   disaster    `json:"dtype"`
	Countries               []country   `json:"countries"`
	NumAffected             any         `json:"num_affected"`
	Severity                int         `json:"ifrc_severity_level"`
	SeverityDisplay         string      `json:"ifrc_severity_level_display"`
	SeverityUpdateDate      string      `json:"ifrc_severity_level_update_date"`
	GLIDE                   string      `json:"glide"`
	DisasterStartDate       string      `json:"disaster_start_date"`
	CreatedAt               string      `json:"created_at"`
	UpdatedAt               string      `json:"updated_at"`
	AutoGenerated           bool        `json:"auto_generated"`
	IsFeatured              bool        `json:"is_featured"`
	IsFeaturedRegion        bool        `json:"is_featured_region"`
	Appeals                 []any       `json:"appeals"`
	FieldReports            []fieldNote `json:"field_reports"`
	TranslationOriginalLang string      `json:"translation_module_original_language"`
}

type disaster struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type country struct {
	ISO  string `json:"iso"`
	ISO3 string `json:"iso3"`
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type fieldNote struct {
	Summary string `json:"summary"`
}

type countryResponse struct {
	Results []countryRecord `json:"results"`
}

type countryRecord struct {
	ISO      string `json:"iso"`
	ISO3     string `json:"iso3"`
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Centroid struct {
		Type        string    `json:"type"`
		Coordinates []float64 `json:"coordinates"`
	} `json:"centroid"`
}

type countryPoint struct {
	Lat  float64
	Lon  float64
	Name string
}

func (c *Collector) Fetch(ctx context.Context) ([]events.Event, error) {
	countries, _ := fetchCountries(ctx)
	var raw eventResponse
	if err := getJSON(ctx, eventsURL, &raw); err != nil {
		return nil, err
	}
	out := make([]events.Event, 0, minInt(len(raw.Results), maxEventCount))
	for _, row := range raw.Results {
		if len(out) >= maxEventCount {
			break
		}
		for _, ev := range eventsFromIFRC(row, countries) {
			out = append(out, ev)
		}
	}
	return dedupe(out), nil
}

func fetchCountries(ctx context.Context) (map[string]countryPoint, error) {
	var raw countryResponse
	if err := getJSON(ctx, countriesURL, &raw); err != nil {
		return nil, err
	}
	out := map[string]countryPoint{}
	for _, c := range raw.Results {
		if len(c.Centroid.Coordinates) < 2 {
			continue
		}
		lon, lat := c.Centroid.Coordinates[0], c.Centroid.Coordinates[1]
		if !validLatLon(lat, lon) {
			continue
		}
		pt := countryPoint{Lat: lat, Lon: lon, Name: c.Name}
		if c.ISO3 != "" {
			out[strings.ToUpper(c.ISO3)] = pt
		}
		if c.ISO != "" {
			out[strings.ToUpper(c.ISO)] = pt
		}
	}
	return out, nil
}

func getJSON(ctx context.Context, rawURL string, out any) error {
	buf, err := exec.CommandContext(ctx, "curl", "-fsS", "-L", "--max-time", "30", "-A", "gordios/0.1", rawURL).Output()
	if err != nil {
		return err
	}
	return json.Unmarshal(buf, out)
}

func eventsFromIFRC(row goEvent, countries map[string]countryPoint) []events.Event {
	ts := firstTime(row.DisasterStartDate, row.CreatedAt, row.UpdatedAt)
	if ts.IsZero() {
		ts = time.Now().UTC()
	}
	disasterType := firstNonEmpty(row.DType.Name, row.Name, "disaster")
	title := strings.TrimSpace(strings.Join(nonEmpty(disasterType, countryNames(row.Countries)), " - "))
	if title == "" {
		title = "IFRC GO event"
	}
	base := map[string]any{
		"source_provider":                 "IFRC GO",
		"source_api_endpoint":             eventsURL,
		"source_public_url":               sourcePublic,
		"source_provider_kind":            sourceKind,
		"event_id":                        row.ID,
		"title":                           title,
		"disaster_type":                   disasterType,
		"disaster_type_id":                row.DType.ID,
		"glide":                           row.GLIDE,
		"ifrc_severity_level":             row.Severity,
		"ifrc_severity_level_display":     row.SeverityDisplay,
		"ifrc_severity_level_update_date": row.SeverityUpdateDate,
		"num_affected":                    row.NumAffected,
		"created_at":                      row.CreatedAt,
		"updated_at":                      row.UpdatedAt,
		"disaster_start_date":             row.DisasterStartDate,
		"auto_generated":                  row.AutoGenerated,
		"is_featured":                     row.IsFeatured,
		"is_featured_region":              row.IsFeaturedRegion,
		"appeal_count":                    len(row.Appeals),
		"field_report_count":              len(row.FieldReports),
		"labels":                          labelsFor(disasterType + " " + title),
		"humanitarian_impact_score":       impactScore(row),
		"source_payload_validity":         validity(ts, row),
	}
	out := []events.Event{}
	for _, c := range row.Countries {
		pt, ok := countries[strings.ToUpper(firstNonEmpty(c.ISO3, c.ISO))]
		if !ok {
			continue
		}
		props := cloneProps(base)
		props["country"] = firstNonEmpty(c.Name, pt.Name)
		props["country_code"] = c.ISO
		props["country_iso3"] = c.ISO3
		props["country_id"] = c.ID
		out = append(out, events.Event{
			Ts:     ts,
			Source: sourceID,
			ExtID:  fmt.Sprintf("ifrc:%d:%s", row.ID, firstNonEmpty(c.ISO3, c.ISO, stableID(c.Name))),
			Lat:    pt.Lat,
			Lon:    pt.Lon,
			Props:  props,
		})
	}
	return out
}

func labelsFor(text string) []string {
	l := strings.ToLower(text)
	out := []string{"humanitarian_disaster"}
	if containsAny(l, "flood", "flash flood") {
		out = append(out, "flood")
	}
	if containsAny(l, "cyclone", "hurricane", "typhoon", "storm") {
		out = append(out, "tropical_cyclone", "severe_weather")
	}
	if containsAny(l, "wildfire", "forest fire") {
		out = append(out, "wildfire")
	}
	if containsAny(l, "earthquake", "tsunami", "volcano", "eruption") {
		out = append(out, "geological_hazard")
	}
	if containsAny(l, "outbreak", "epidemic", "dengue", "cholera", "ebola") {
		out = append(out, "health_outbreak")
	}
	return unique(out)
}

func impactScore(row goEvent) float64 {
	score := 0.4
	switch strings.ToLower(row.SeverityDisplay) {
	case "red":
		score += 2.2
	case "orange":
		score += 1.5
	case "yellow":
		score += 0.8
	}
	if row.Severity > 0 {
		score = math.Max(score, propx.ClampFloat(float64(row.Severity)*0.55, 0, 2.5))
	}
	if affected, ok := floatAny(row.NumAffected); ok && affected > 0 {
		score += propx.ClampFloat(math.Log10(affected+1)/4.0, 0, 1.0)
	}
	if len(row.Appeals) > 0 {
		score += 0.4
	}
	if len(row.FieldReports) > 0 {
		score += 0.3
	}
	return propx.ClampFloat(score, 0, 3)
}

func validity(ts time.Time, row goEvent) map[string]any {
	end := firstTime(row.SeverityUpdateDate, row.UpdatedAt, row.CreatedAt)
	if end.IsZero() || end.Before(ts) {
		end = ts.Add(14 * 24 * time.Hour)
	}
	return map[string]any{
		"valid_start":    ts.Format(time.RFC3339),
		"valid_end":      end.Format(time.RFC3339),
		"validity_basis": "ifrc_go_disaster_active_context_window",
	}
}

func cloneProps(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func countryNames(cs []country) string {
	names := []string{}
	for _, c := range cs {
		if c.Name != "" {
			names = append(names, c.Name)
		}
	}
	return strings.Join(names, ", ")
}

func firstTime(vals ...string) time.Time {
	for _, v := range vals {
		if t := parseTime(v); !t.IsZero() {
			return t
		}
	}
	return time.Time{}
}

func parseTime(s string) time.Time {
	s = strings.TrimSpace(s)
	if s == "" || strings.EqualFold(s, "null") {
		return time.Time{}
	}
	for _, layout := range []string{time.RFC3339Nano, time.RFC3339, "2006-01-02T15:04:05Z", "2006-01-02"} {
		if t, err := time.Parse(layout, s); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

func floatAny(v any) (float64, bool) {
	switch x := v.(type) {
	case float64:
		return x, true
	case float32:
		return float64(x), true
	case int:
		return float64(x), true
	case int64:
		return float64(x), true
	case json.Number:
		f, err := x.Float64()
		return f, err == nil
	case string:
		var f float64
		if _, err := fmt.Sscanf(strings.TrimSpace(x), "%f", &f); err == nil {
			return f, true
		}
	}
	return 0, false
}

func validLatLon(lat, lon float64) bool {
	return !math.IsNaN(lat) && !math.IsNaN(lon) && lat >= -90 && lat <= 90 && lon >= -180 && lon <= 180 && (lat != 0 || lon != 0)
}

func containsAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, strings.ToLower(sub)) {
			return true
		}
	}
	return false
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

func nonEmpty(vals ...string) []string {
	out := []string{}
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			out = append(out, strings.TrimSpace(v))
		}
	}
	return out
}

func unique(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, v := range in {
		v = strings.TrimSpace(v)
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	return out
}

func dedupe(in []events.Event) []events.Event {
	seen := map[string]bool{}
	out := make([]events.Event, 0, len(in))
	for _, e := range in {
		if e.Source == "" || e.ExtID == "" || !e.HasPoint() {
			continue
		}
		key := e.Source + ":" + e.ExtID
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, e)
	}
	return out
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func stableID(s string) string {
	h := sha1.Sum([]byte(strings.ToLower(strings.TrimSpace(s))))
	return hex.EncodeToString(h[:])
}
